/*CREAMOS LA BASE DE DATOS*/
CREATE DATABASE SCHOOL;

/*CREAMOS UN USUARIO ADMINISTRADOR*/
CREATE USER ADMINISTRADOR PASSWORD 'kX+TfcF82bf;i=|tk7{6';

--ASIGNAMOS PERMISOS SOBRE LA BASE DE DATOS
GRANT ALL PRIVILEGES ON DATABASE SCHOOL to ADMINISTRADOR;


