CREATE TABLE LEARNING_ENGLISH.THEME(
TH_ID INTEGER,
TH_NAME VARCHAR(100),
TH_DESCRIPTION VARCHAR(100),
TH_KEYWORDS TEXT,
TH_ICON VARCHAR(100),
TH_STATE BOOLEAN NOT NULL,
TH_ORDER INTEGER
);

/*PRIMARY KEY*/
ALTER TABLE LEARNING_ENGLISH.THEME ADD CONSTRAINT THEME_PK PRIMARY KEY (TH_ID);

/*COMMENT THE TABLE*/
COMMENT ON TABLE LEARNING_ENGLISH.THEME IS 'This table stores the different types of thems';
/*COMMENT THE FIELDS*/
COMMENT ON COLUMN LEARNING_ENGLISH.THEME.TH_ID IS 'Primary key of the table THEME.';
COMMENT ON COLUMN LEARNING_ENGLISH.THEME.TH_NAME IS 'Field that saves the name of the lesson.';
COMMENT ON COLUMN LEARNING_ENGLISH.THEME.TH_DESCRIPTION IS 'Field that saves the description of the theme.';
COMMENT ON COLUMN LEARNING_ENGLISH.THEME.TH_KEYWORDS IS 'Field that saves the keywords of the theme.';
COMMENT ON COLUMN LEARNING_ENGLISH.THEME.TH_ICON IS 'Field that saves the icon of the lesson.';
COMMENT ON COLUMN LEARNING_ENGLISH.THEME.TH_STATE IS 'Field that saves the state of the theme.';
COMMENT ON COLUMN LEARNING_ENGLISH.THEME.TH_ORDER IS 'Field that saves the order of the theme.';
;