DELETE FROM LEARNING_ENGLISH.THEME;

/*INSERTS*/
INSERT INTO LEARNING_ENGLISH.THEME (TH_ID, TH_NAME, TH_KEYWORDS, TH_ICON, TH_STATE, TH_ORDER) VALUES (1, 'THE ALPHABET', 'ALPHABET', 'icon-alphabet2', TRUE, 1);
INSERT INTO LEARNING_ENGLISH.THEME (TH_ID, TH_NAME, TH_KEYWORDS, TH_ICON, TH_STATE, TH_ORDER) VALUES (2, 'THE COLORS', 'COLOR|COLORS', 'icon-colors', TRUE, 2);
INSERT INTO LEARNING_ENGLISH.THEME (TH_ID, TH_NAME, TH_KEYWORDS, TH_ICON, TH_STATE, TH_ORDER) VALUES (3, 'THE NUMBERS', 'NUMBER|NUMBERS', 'icon-numbers2', TRUE, 3);
INSERT INTO LEARNING_ENGLISH.THEME (TH_ID, TH_NAME, TH_KEYWORDS, TH_ICON, TH_STATE, TH_ORDER) VALUES (4, 'MATHEMATICAL SYMBOLS', 'MATHEMATICAL|SYMBOL|SYMBOLS', 'icon-mathematical-symbol', TRUE, 4);
INSERT INTO LEARNING_ENGLISH.THEME (TH_ID, TH_NAME, TH_KEYWORDS, TH_ICON, TH_STATE, TH_ORDER) VALUES (5, 'GREETINGS', 'GREETING|GREETINGS', 'icon-greetings', TRUE, 5);
INSERT INTO LEARNING_ENGLISH.THEME (TH_ID, TH_NAME, TH_KEYWORDS, TH_ICON, TH_STATE, TH_ORDER) VALUES (6, 'THE DAYS OF THE WEEK', 'DAY|DAYS|WEEK', 'icon-days-of-the-Week', TRUE, 6);
INSERT INTO LEARNING_ENGLISH.THEME (TH_ID, TH_NAME, TH_KEYWORDS, TH_ICON, TH_STATE, TH_ORDER) VALUES (7, 'THE MONTHS OF THE YEAR', 'MONTH|MONTHS|YEAR|CALENDAR', 'icon-months-of-the-year', TRUE, 7);
INSERT INTO LEARNING_ENGLISH.THEME (TH_ID, TH_NAME, TH_KEYWORDS, TH_ICON, TH_STATE, TH_ORDER) VALUES (8, 'THE ADJECTIVES', 'ADJECTIVE|ADJECTIVES', 'icon-happy', TRUE, 8);
INSERT INTO LEARNING_ENGLISH.THEME (TH_ID, TH_NAME, TH_KEYWORDS, TH_ICON, TH_STATE, TH_ORDER) VALUES (9, 'THE ARTICLES', 'ARTICLE|ARTICLES', 'icon-articles', TRUE, 9);
INSERT INTO LEARNING_ENGLISH.THEME (TH_ID, TH_NAME, TH_KEYWORDS, TH_ICON, TH_STATE, TH_ORDER) VALUES (10, 'THE NOUNS', 'NOUN|NOUNS|PLURAL|PLURALS', 'icon-plural', TRUE, 10);
INSERT INTO LEARNING_ENGLISH.THEME (TH_ID, TH_NAME, TH_KEYWORDS, TH_ICON, TH_STATE, TH_ORDER) VALUES (11, 'PRESENT SIMPLE TENSE', 'PRESENT|SIMPLE|TENSE', 'icon-education', TRUE, 11);
INSERT INTO LEARNING_ENGLISH.THEME (TH_ID, TH_NAME, TH_KEYWORDS, TH_ICON, TH_STATE, TH_ORDER) VALUES (12, 'THE TIME', 'TIME', 'icon-clock', TRUE, 12);
INSERT INTO LEARNING_ENGLISH.THEME (TH_ID, TH_NAME, TH_KEYWORDS, TH_ICON, TH_STATE, TH_ORDER) VALUES (13, 'THE VERBS', 'VERB|VERBS', 'icon-list', TRUE, 13);
INSERT INTO LEARNING_ENGLISH.THEME (TH_ID, TH_NAME, TH_KEYWORDS, TH_ICON, TH_STATE, TH_ORDER) VALUES (14, 'THE WEATHER', 'WEATHER', 'icon-weather', TRUE, 14);
INSERT INTO LEARNING_ENGLISH.THEME (TH_ID, TH_NAME, TH_KEYWORDS, TH_ICON, TH_STATE, TH_ORDER) VALUES (15, 'THE FAMILY', 'FAMILY', 'icon-the-family', TRUE, 15);
INSERT INTO LEARNING_ENGLISH.THEME (TH_ID, TH_NAME, TH_KEYWORDS, TH_ICON, TH_STATE, TH_ORDER) VALUES (16, 'THE PROFESSIONS', 'PROFESSION|PROFESSIONS', 'icon-professions', TRUE, 16);
INSERT INTO LEARNING_ENGLISH.THEME (TH_ID, TH_NAME, TH_KEYWORDS, TH_ICON, TH_STATE, TH_ORDER) VALUES (17, 'THE SCHOOL', 'SCHOOL', 'icon-school', TRUE, 17);
INSERT INTO LEARNING_ENGLISH.THEME (TH_ID, TH_NAME, TH_KEYWORDS, TH_ICON, TH_STATE, TH_ORDER) VALUES (18, 'WRITING', 'WRITING', 'icon-writing', TRUE, 18);
INSERT INTO LEARNING_ENGLISH.THEME (TH_ID, TH_NAME, TH_KEYWORDS, TH_ICON, TH_STATE, TH_ORDER) VALUES (19, 'PREPOSITIONS OF PLACE', 'PREPOSITION|PREPOSITIONS|PLACE', 'icon-prepositions-of-Place', TRUE, 19);
INSERT INTO LEARNING_ENGLISH.THEME (TH_ID, TH_NAME, TH_KEYWORDS, TH_ICON, TH_STATE, TH_ORDER) VALUES (20, 'PARTS OF THE BODY', 'PARTS|BODY', 'icon-head', TRUE, 20);
INSERT INTO LEARNING_ENGLISH.THEME (TH_ID, TH_NAME, TH_KEYWORDS, TH_ICON, TH_STATE, TH_ORDER) VALUES (21, 'THE ANIMAL KINGDOM', 'ANIMAL|ANIMALS|KINGDOM', 'icon-footprint', TRUE, 21);
INSERT INTO LEARNING_ENGLISH.THEME (TH_ID, TH_NAME, TH_KEYWORDS, TH_ICON, TH_STATE, TH_ORDER) VALUES (22, 'PLACES AND BUILDINGS', 'PLACE|PLACES|BUILDING|BUILDINGS', 'icon-airport', TRUE, 22);
INSERT INTO LEARNING_ENGLISH.THEME (TH_ID, TH_NAME, TH_KEYWORDS, TH_ICON, TH_STATE, TH_ORDER) VALUES (23, 'GEOGRAPHIC FEATURES', 'GEOGRAPHIC|FEATURES', 'icon-island', TRUE, 23);
INSERT INTO LEARNING_ENGLISH.THEME (TH_ID, TH_NAME, TH_KEYWORDS, TH_ICON, TH_STATE, TH_ORDER) VALUES (24, 'THE ILLNESSES', 'ILLNESS|ILLNESSES', 'icon-ill', TRUE, 24);
INSERT INTO LEARNING_ENGLISH.THEME (TH_ID, TH_NAME, TH_KEYWORDS, TH_ICON, TH_STATE, TH_ORDER) VALUES (25, 'THE SEASONS', 'SEASON|SEASONS', 'icon-seasons', TRUE, 25);
INSERT INTO LEARNING_ENGLISH.THEME (TH_ID, TH_NAME, TH_KEYWORDS, TH_ICON, TH_STATE, TH_ORDER) VALUES (26, 'CARDINAL POINTS', 'CARDINAL|POINTS', 'icon-cardinal-points', TRUE, 26);

