DELETE FROM LEARNING_ENGLISH.LESSON_TYPE;

/*INSERTS*/
INSERT INTO LEARNING_ENGLISH.LESSON_TYPE (LT_ID, LT_VALUE) VALUES (1, 'GRAMMAR');
INSERT INTO LEARNING_ENGLISH.LESSON_TYPE (LT_ID, LT_VALUE) VALUES (2, 'GRAPHICS IMAGES');
INSERT INTO LEARNING_ENGLISH.LESSON_TYPE (LT_ID, LT_VALUE) VALUES (3, 'GRAPHICS TEXTS');
INSERT INTO LEARNING_ENGLISH.LESSON_TYPE (LT_ID, LT_VALUE) VALUES (4, 'CUSTOM');
INSERT INTO LEARNING_ENGLISH.LESSON_TYPE (LT_ID, LT_VALUE) VALUES (5, 'VOCABULARY');