CREATE TABLE LEARNING_ENGLISH.LESSON_TYPE(
LT_ID INTEGER,
LT_VALUE VARCHAR(100)
);

/*PRIMARY KEY*/
ALTER TABLE LEARNING_ENGLISH.LESSON_TYPE ADD CONSTRAINT LESSON_TYPE_PK PRIMARY KEY (LT_ID);
/*UNIQUE*/
ALTER TABLE LEARNING_ENGLISH.LESSON_TYPE ADD CONSTRAINT LESSON_TYPE_UN UNIQUE (LT_VALUE);

/*COMMENT THE TABLE*/
COMMENT ON TABLE LEARNING_ENGLISH.LESSON_TYPE IS 'This table stores the lesson type';
/*COMMENT THE FIELDS*/
COMMENT ON COLUMN LEARNING_ENGLISH.LESSON_TYPE.LT_ID IS 'Primary key of the table LESSON_TYPE.';
COMMENT ON COLUMN LEARNING_ENGLISH.LESSON_TYPE.LT_VALUE IS 'Field that saves the lesson type value.';