DELETE FROM LEARNING_ENGLISH.LESSON;

/*INSERTS*/
INSERT INTO LEARNING_ENGLISH.LESSON (LE_ID, LE_ID_THEME, LE_ID_LESSON_TYPE, LE_NAME, LE_ICON, LE_STATE, LE_ORDER) VALUES ('1_1', 1, 3, 'the alphabet pronunciation', 'icon-alphabet2', TRUE, 1);
INSERT INTO LEARNING_ENGLISH.LESSON (LE_ID, LE_ID_THEME, LE_ID_LESSON_TYPE, LE_NAME, LE_ICON, LE_STATE, LE_ORDER) VALUES ('2_1', 2, 4, 'the colors', 'icon-colors', TRUE, 1);

INSERT INTO LEARNING_ENGLISH.LESSON (LE_ID, LE_ID_THEME, LE_ID_LESSON_TYPE, LE_NAME, LE_ICON, LE_STATE, LE_ORDER) VALUES ('3_1', 3, 3, 'the numbers', 'icon-numbers', TRUE, 1);
INSERT INTO LEARNING_ENGLISH.LESSON (LE_ID, LE_ID_THEME, LE_ID_LESSON_TYPE, LE_NAME, LE_ICON, LE_STATE, LE_ORDER) VALUES ('3_2', 3, 3, 'the ordinal numbers', 'icon-ordinal-numbers', TRUE, 2);

INSERT INTO LEARNING_ENGLISH.LESSON (LE_ID, LE_ID_THEME, LE_ID_LESSON_TYPE, LE_NAME, LE_ICON, LE_STATE, LE_ORDER) VALUES ('4_1', 4, 3, 'mathematical symbols', 'icon-mathematical-symbol', TRUE, 1);
INSERT INTO LEARNING_ENGLISH.LESSON (LE_ID, LE_ID_THEME, LE_ID_LESSON_TYPE, LE_NAME, LE_ICON, LE_STATE, LE_ORDER) VALUES ('5_1', 5, 5, 'greetings and farewells', 'icon-greetings', TRUE, 1);
INSERT INTO LEARNING_ENGLISH.LESSON (LE_ID, LE_ID_THEME, LE_ID_LESSON_TYPE, LE_NAME, LE_ICON, LE_STATE, LE_ORDER) VALUES ('6_1', 6, 5, 'the days of the week', 'icon-days-of-the-Week', TRUE, 1);
INSERT INTO LEARNING_ENGLISH.LESSON (LE_ID, LE_ID_THEME, LE_ID_LESSON_TYPE, LE_NAME, LE_ICON, LE_STATE, LE_ORDER) VALUES ('7_1', 7, 5, 'the months of the year', 'icon-months-of-the-year', TRUE, 1);


INSERT INTO LEARNING_ENGLISH.LESSON (LE_ID, LE_ID_THEME, LE_ID_LESSON_TYPE, LE_NAME, LE_ICON, LE_STATE, LE_ORDER) VALUES ('8_1', 8, 5, 'the adjetives', 'icon-happy', TRUE, 1);
INSERT INTO LEARNING_ENGLISH.LESSON (LE_ID, LE_ID_THEME, LE_ID_LESSON_TYPE, LE_NAME, LE_ICON, LE_STATE, LE_ORDER) VALUES ('9_1', 9, 5, 'the articles', 'icon-articles', TRUE, 1);
INSERT INTO LEARNING_ENGLISH.LESSON (LE_ID, LE_ID_THEME, LE_ID_LESSON_TYPE, LE_NAME, LE_ICON, LE_STATE, LE_ORDER) VALUES ('10_1', 10, 5, 'the nouns', 'icon-plural', TRUE, 3);

INSERT INTO LEARNING_ENGLISH.LESSON (LE_ID, LE_ID_THEME, LE_ID_LESSON_TYPE, LE_NAME, LE_ICON, LE_STATE, LE_ORDER) VALUES ('11_1', 11, 5, '3rd person rules', 'icon-numbered-list', TRUE, 1);
INSERT INTO LEARNING_ENGLISH.LESSON (LE_ID, LE_ID_THEME, LE_ID_LESSON_TYPE, LE_NAME, LE_ICON, LE_STATE, LE_ORDER) VALUES ('11_2', 11, 5, 'personal pronouns', 'icon-personal-pronouns', TRUE, 2);
INSERT INTO LEARNING_ENGLISH.LESSON (LE_ID, LE_ID_THEME, LE_ID_LESSON_TYPE, LE_NAME, LE_ICON, LE_STATE, LE_ORDER) VALUES ('11_3', 11, 5, 'the verb to be', 'icon-verb-to-be', TRUE, 3);

INSERT INTO LEARNING_ENGLISH.LESSON (LE_ID, LE_ID_THEME, LE_ID_LESSON_TYPE, LE_NAME, LE_ICON, LE_STATE, LE_ORDER) VALUES ('12_1', 12, 5, 'the time', 'icon-clock', TRUE, 1);

INSERT INTO LEARNING_ENGLISH.LESSON (LE_ID, LE_ID_THEME, LE_ID_LESSON_TYPE, LE_NAME, LE_ICON, LE_STATE, LE_ORDER) VALUES ('13_1', 13, 4, 'the regular verbs', 'icon-list', TRUE, 1);
INSERT INTO LEARNING_ENGLISH.LESSON (LE_ID, LE_ID_THEME, LE_ID_LESSON_TYPE, LE_NAME, LE_ICON, LE_STATE, LE_ORDER) VALUES ('13_2', 13, 4, 'the irregular verbs', 'icon-list2', TRUE, 2);

INSERT INTO LEARNING_ENGLISH.LESSON (LE_ID, LE_ID_THEME, LE_ID_LESSON_TYPE, LE_NAME, LE_ICON, LE_STATE, LE_ORDER) VALUES ('14_1', 14, 2, 'the weather', 'icon-weather', TRUE, 1);
INSERT INTO LEARNING_ENGLISH.LESSON (LE_ID, LE_ID_THEME, LE_ID_LESSON_TYPE, LE_NAME, LE_ICON, LE_STATE, LE_ORDER) VALUES ('14_2', 14, 2, 'The Temperature', 'icon-temperature', TRUE, 2);

INSERT INTO LEARNING_ENGLISH.LESSON (LE_ID, LE_ID_THEME, LE_ID_LESSON_TYPE, LE_NAME, LE_ICON, LE_STATE, LE_ORDER) VALUES ('15_1', 15, 2, 'the family', 'icon-the-family', TRUE, 1);
INSERT INTO LEARNING_ENGLISH.LESSON (LE_ID, LE_ID_THEME, LE_ID_LESSON_TYPE, LE_NAME, LE_ICON, LE_STATE, LE_ORDER) VALUES ('16_1', 16, 2, 'the professions', 'icon-professions', TRUE, 1);

INSERT INTO LEARNING_ENGLISH.LESSON (LE_ID, LE_ID_THEME, LE_ID_LESSON_TYPE, LE_NAME, LE_ICON, LE_STATE, LE_ORDER) VALUES ('17_1', 17, 2, 'the school objects', 'icon-school3', TRUE, 1);
INSERT INTO LEARNING_ENGLISH.LESSON (LE_ID, LE_ID_THEME, LE_ID_LESSON_TYPE, LE_NAME, LE_ICON, LE_STATE, LE_ORDER) VALUES ('17_2', 17, 5, 'subjects', 'icon-subjects', TRUE, 2);
INSERT INTO LEARNING_ENGLISH.LESSON (LE_ID, LE_ID_THEME, LE_ID_LESSON_TYPE, LE_NAME, LE_ICON, LE_STATE, LE_ORDER) VALUES ('17_3', 17, 5, 'timetable', 'icon-timetable', TRUE, 3);

INSERT INTO LEARNING_ENGLISH.LESSON (LE_ID, LE_ID_THEME, LE_ID_LESSON_TYPE, LE_NAME, LE_ICON, LE_STATE, LE_ORDER) VALUES ('18_1', 18, 5, 'writing', 'icon-writing', TRUE, 1);
INSERT INTO LEARNING_ENGLISH.LESSON (LE_ID, LE_ID_THEME, LE_ID_LESSON_TYPE, LE_NAME, LE_ICON, LE_STATE, LE_ORDER) VALUES ('19_1', 19, 5, 'prepositions of place', 'icon-prepositions-of-Place', TRUE, 1);
INSERT INTO LEARNING_ENGLISH.LESSON (LE_ID, LE_ID_THEME, LE_ID_LESSON_TYPE, LE_NAME, LE_ICON, LE_STATE, LE_ORDER) VALUES ('20_1', 20, 5, 'parts of the body', 'icon-head', TRUE, 1);

INSERT INTO LEARNING_ENGLISH.LESSON (LE_ID, LE_ID_THEME, LE_ID_LESSON_TYPE, LE_NAME, LE_ICON, LE_STATE, LE_ORDER) VALUES ('21_1', 21, 2, 'the animals', 'icon-animals', TRUE, 1);
INSERT INTO LEARNING_ENGLISH.LESSON (LE_ID, LE_ID_THEME, LE_ID_LESSON_TYPE, LE_NAME, LE_ICON, LE_STATE, LE_ORDER) VALUES ('21_2', 21, 2, 'the animal body parts', 'icon-feather', TRUE, 2);

INSERT INTO LEARNING_ENGLISH.LESSON (LE_ID, LE_ID_THEME, LE_ID_LESSON_TYPE, LE_NAME, LE_ICON, LE_STATE, LE_ORDER) VALUES ('22_1', 22, 5, 'places and buildings', 'icon-airport', TRUE, 1);
INSERT INTO LEARNING_ENGLISH.LESSON (LE_ID, LE_ID_THEME, LE_ID_LESSON_TYPE, LE_NAME, LE_ICON, LE_STATE, LE_ORDER) VALUES ('23_1', 23, 5, 'geographic features', 'icon-island', TRUE, 1);
INSERT INTO LEARNING_ENGLISH.LESSON (LE_ID, LE_ID_THEME, LE_ID_LESSON_TYPE, LE_NAME, LE_ICON, LE_STATE, LE_ORDER) VALUES ('24_1', 24, 5, 'the illnesses', 'icon-ill', TRUE, 1);
INSERT INTO LEARNING_ENGLISH.LESSON (LE_ID, LE_ID_THEME, LE_ID_LESSON_TYPE, LE_NAME, LE_ICON, LE_STATE, LE_ORDER) VALUES ('25_1', 25, 2, 'the seasons', 'icon-seasons', TRUE, 1);
INSERT INTO LEARNING_ENGLISH.LESSON (LE_ID, LE_ID_THEME, LE_ID_LESSON_TYPE, LE_NAME, LE_ICON, LE_STATE, LE_ORDER) VALUES ('26_1', 26, 5, 'cardinal points', 'icon-cardinal-points', TRUE, 1);




