DELETE FROM LEARNING_ENGLISH.VOCABULARY WHERE VO_ID_LESSON = '2_1';

INSERT INTO LEARNING_ENGLISH.VOCABULARY (VO_ID_LESSON, VO_ENGLISH_VALUE, VO_ENGLISH_SOUND, VO_SPANISH_VALUE, VO_SPANISH_SOUND, VO_OTHER_VALUE) VALUES ('2_1', 'BLACK', 'BLACK.MP3', 'NEGRO', 'NEGRO.MP3', '#000000');
INSERT INTO LEARNING_ENGLISH.VOCABULARY (VO_ID_LESSON, VO_ENGLISH_VALUE, VO_ENGLISH_SOUND, VO_SPANISH_VALUE, VO_SPANISH_SOUND, VO_OTHER_VALUE) VALUES ('2_1', 'BLUE', 'BLUE.MP3', 'AZUL', 'AZUL.MP3', '#013ADF');
INSERT INTO LEARNING_ENGLISH.VOCABULARY (VO_ID_LESSON, VO_ENGLISH_VALUE, VO_ENGLISH_SOUND, VO_SPANISH_VALUE, VO_SPANISH_SOUND, VO_OTHER_VALUE) VALUES ('2_1', 'BROWN', 'BROWN.MP3', 'MARRÓN', 'MARRÓN.MP3', '#472914');
INSERT INTO LEARNING_ENGLISH.VOCABULARY (VO_ID_LESSON, VO_ENGLISH_VALUE, VO_ENGLISH_SOUND, VO_SPANISH_VALUE, VO_SPANISH_SOUND, VO_OTHER_VALUE) VALUES ('2_1', 'CHESTNUT', 'CHESTNUT.MP3', 'CASTAÑO', 'CASTAÑO.MP3', '#4c1e1b');
INSERT INTO LEARNING_ENGLISH.VOCABULARY (VO_ID_LESSON, VO_ENGLISH_VALUE, VO_ENGLISH_SOUND, VO_SPANISH_VALUE, VO_SPANISH_SOUND, VO_OTHER_VALUE) VALUES ('2_1', 'FUCHSIA', 'FUCHSIA.MP3', 'FUCSIA', 'FUCSIA.MP3', '#f300a0');
INSERT INTO LEARNING_ENGLISH.VOCABULARY (VO_ID_LESSON, VO_ENGLISH_VALUE, VO_ENGLISH_SOUND, VO_SPANISH_VALUE, VO_SPANISH_SOUND, VO_OTHER_VALUE) VALUES ('2_1', 'GOLDEN', 'GOLDEN.MP3', 'DORADO', 'DORADO.MP3', '#d1a505');
INSERT INTO LEARNING_ENGLISH.VOCABULARY (VO_ID_LESSON, VO_ENGLISH_VALUE, VO_ENGLISH_SOUND, VO_SPANISH_VALUE, VO_SPANISH_SOUND, VO_OTHER_VALUE) VALUES ('2_1', 'GREEN', 'GREEN.MP3', 'VERDE', 'VERDE.MP3', '#04B404');
INSERT INTO LEARNING_ENGLISH.VOCABULARY (VO_ID_LESSON, VO_ENGLISH_VALUE, VO_ENGLISH_SOUND, VO_SPANISH_VALUE, VO_SPANISH_SOUND, VO_OTHER_VALUE) VALUES ('2_1', 'GREY', 'GREY.MP3', 'GRIS', 'GRIS.MP3', '#808080');
INSERT INTO LEARNING_ENGLISH.VOCABULARY (VO_ID_LESSON, VO_ENGLISH_VALUE, VO_ENGLISH_SOUND, VO_SPANISH_VALUE, VO_SPANISH_SOUND, VO_OTHER_VALUE) VALUES ('2_1', 'IVORY', 'IVORY.MP3', 'MARFIL', 'MARFIL.MP3', '#ffffef');
INSERT INTO LEARNING_ENGLISH.VOCABULARY (VO_ID_LESSON, VO_ENGLISH_VALUE, VO_ENGLISH_SOUND, VO_SPANISH_VALUE, VO_SPANISH_SOUND, VO_OTHER_VALUE) VALUES ('2_1', 'ORANGE', 'ORANGE.MP3', 'NARANJA', 'NARANJA.MP3', '#FF4000');
INSERT INTO LEARNING_ENGLISH.VOCABULARY (VO_ID_LESSON, VO_ENGLISH_VALUE, VO_ENGLISH_SOUND, VO_SPANISH_VALUE, VO_SPANISH_SOUND, VO_OTHER_VALUE) VALUES ('2_1', 'PINK', 'PINK.MP3', 'ROSADO', 'ROSADO.MP3', '#ff99cc');
INSERT INTO LEARNING_ENGLISH.VOCABULARY (VO_ID_LESSON, VO_ENGLISH_VALUE, VO_ENGLISH_SOUND, VO_SPANISH_VALUE, VO_SPANISH_SOUND, VO_OTHER_VALUE) VALUES ('2_1', 'PURPLE', 'PURPLE.MP3', 'PÚRPURA', 'PÚRPURA.MP3', '#560456');
INSERT INTO LEARNING_ENGLISH.VOCABULARY (VO_ID_LESSON, VO_ENGLISH_VALUE, VO_ENGLISH_SOUND, VO_SPANISH_VALUE, VO_SPANISH_SOUND, VO_OTHER_VALUE) VALUES ('2_1', 'RED', 'RED.MP3', 'ROJO', 'ROJO.MP3', '#DF0101');
INSERT INTO LEARNING_ENGLISH.VOCABULARY (VO_ID_LESSON, VO_ENGLISH_VALUE, VO_ENGLISH_SOUND, VO_SPANISH_VALUE, VO_SPANISH_SOUND, VO_OTHER_VALUE) VALUES ('2_1', 'SILVER', 'SILVER.MP3', 'PLATEADO', 'PLATEADO.MP3', '#8693a5');
INSERT INTO LEARNING_ENGLISH.VOCABULARY (VO_ID_LESSON, VO_ENGLISH_VALUE, VO_ENGLISH_SOUND, VO_SPANISH_VALUE, VO_SPANISH_SOUND, VO_OTHER_VALUE) VALUES ('2_1', 'VIOLET', 'VIOLET.MP3', 'VIOLETA', 'VIOLETA.MP3', '#991099');
INSERT INTO LEARNING_ENGLISH.VOCABULARY (VO_ID_LESSON, VO_ENGLISH_VALUE, VO_ENGLISH_SOUND, VO_SPANISH_VALUE, VO_SPANISH_SOUND, VO_OTHER_VALUE) VALUES ('2_1', 'WHITE', 'WHITE.MP3', 'BLANCO', 'BLANCO.MP3', '#ffffff');
INSERT INTO LEARNING_ENGLISH.VOCABULARY (VO_ID_LESSON, VO_ENGLISH_VALUE, VO_ENGLISH_SOUND, VO_SPANISH_VALUE, VO_SPANISH_SOUND, VO_OTHER_VALUE) VALUES ('2_1', 'YELLOW', 'YELLOW.MP3', 'AMARILLO', 'AMARILLO.MP3', '#FFFF00');


