DELETE FROM ENGLISH_LAB.VOCABULARY WHERE ID_LESSON = '5_1';

INSERT INTO ENGLISH_LAB.VOCABULARY (ID_LESSON, ENGLISH_VALUE, ENGLISH_SOUND, SPANISH_VALUE, SPANISH_SOUND, "ORDER") VALUES ('5_1', 'GOOD MORNING', 'GOOD MORNING.MP3', 'BUENOS DÍAS', 'BUENOS DÍAS.MP3', 1);
INSERT INTO ENGLISH_LAB.VOCABULARY (ID_LESSON, ENGLISH_VALUE, ENGLISH_SOUND, SPANISH_VALUE, SPANISH_SOUND, "ORDER") VALUES ('5_1', 'GOOD AFTERNOON', 'GOOD AFTERNOON.MP3', 'BUENAS TARDES', 'BUENAS TARDES.MP3', 2);
INSERT INTO ENGLISH_LAB.VOCABULARY (ID_LESSON, ENGLISH_VALUE, ENGLISH_SOUND, SPANISH_VALUE, SPANISH_SOUND, "ORDER") VALUES ('5_1', 'GOOD EVENING ', 'GOOD EVENING .MP3', 'BUENAS NOCHES (SALUDO)', 'BUENAS NOCHES (SALUDO).MP3', 3);
INSERT INTO ENGLISH_LAB.VOCABULARY (ID_LESSON, ENGLISH_VALUE, ENGLISH_SOUND, SPANISH_VALUE, SPANISH_SOUND, "ORDER") VALUES ('5_1', 'GOOD NIGHT ', 'GOOD NIGHT .MP3', 'BUENAS NOCHES (AL DESPEDIRSE)', 'BUENAS NOCHES (AL DESPEDIRSE).MP3', 4);
INSERT INTO ENGLISH_LAB.VOCABULARY (ID_LESSON, ENGLISH_VALUE, ENGLISH_SOUND, SPANISH_VALUE, SPANISH_SOUND, "ORDER") VALUES ('5_1', 'GOOD-BYE', 'GOOD-BYE.MP3', 'ADIÓS', 'ADIÓS.MP3', 5);
INSERT INTO ENGLISH_LAB.VOCABULARY (ID_LESSON, ENGLISH_VALUE, ENGLISH_SOUND, SPANISH_VALUE, SPANISH_SOUND, "ORDER") VALUES ('5_1', 'HAVE A NICE DAY', 'HAVE A NICE DAY.MP3', 'QUÉ PASES UN LINDO DÍA', 'QUÉ PASES UN LINDO DÍA.MP3', 6);
INSERT INTO ENGLISH_LAB.VOCABULARY (ID_LESSON, ENGLISH_VALUE, ENGLISH_SOUND, SPANISH_VALUE, SPANISH_SOUND, "ORDER") VALUES ('5_1', 'HELLO', 'HELLO.MP3', 'HOLA', 'HOLA.MP3', 7);
INSERT INTO ENGLISH_LAB.VOCABULARY (ID_LESSON, ENGLISH_VALUE, ENGLISH_SOUND, SPANISH_VALUE, SPANISH_SOUND, "ORDER") VALUES ('5_1', 'HI', 'HI.MP3', 'HOLA', 'HOLA.MP3', 8);
INSERT INTO ENGLISH_LAB.VOCABULARY (ID_LESSON, ENGLISH_VALUE, ENGLISH_SOUND, SPANISH_VALUE, SPANISH_SOUND, "ORDER") VALUES ('5_1', 'SEE YOU AT NOON', 'SEE YOU AT NOON.MP3', 'HASTA EL MEDIO DÍA', 'HASTA EL MEDIO DÍA.MP3', 9);
INSERT INTO ENGLISH_LAB.VOCABULARY (ID_LESSON, ENGLISH_VALUE, ENGLISH_SOUND, SPANISH_VALUE, SPANISH_SOUND, "ORDER") VALUES ('5_1', 'SEE YOU IN THE EVENING', 'SEE YOU IN THE EVENING.MP3', 'NOS VEMOS EN LA NOCHE', 'NOS VEMOS EN LA NOCHE.MP3', 10);
INSERT INTO ENGLISH_LAB.VOCABULARY (ID_LESSON, ENGLISH_VALUE, ENGLISH_SOUND, SPANISH_VALUE, SPANISH_SOUND, "ORDER") VALUES ('5_1', 'SEE YOU SOON', 'SEE YOU SOON.MP3', 'HASTA PRONTO', 'HASTA PRONTO.MP3', 11);
INSERT INTO ENGLISH_LAB.VOCABULARY (ID_LESSON, ENGLISH_VALUE, ENGLISH_SOUND, SPANISH_VALUE, SPANISH_SOUND, "ORDER") VALUES ('5_1', 'SEE YOU TOMORROW', 'SEE YOU TOMORROW.MP3', 'HASTA MAÑANA', 'HASTA MAÑANA.MP3', 12);
INSERT INTO ENGLISH_LAB.VOCABULARY (ID_LESSON, ENGLISH_VALUE, ENGLISH_SOUND, SPANISH_VALUE, SPANISH_SOUND, "ORDER") VALUES ('5_1', 'SO LONG', 'SO LONG.MP3', 'HASTA LUEGO/NOS VEMOS', 'HASTA LUEGO/NOS VEMOS.MP3', 13);
INSERT INTO ENGLISH_LAB.VOCABULARY (ID_LESSON, ENGLISH_VALUE, ENGLISH_SOUND, SPANISH_VALUE, SPANISH_SOUND, "ORDER") VALUES ('5_1', 'SO LONG! SEE YOU LATER', 'SO LONG! SEE YOU LATER.MP3', 'NOS VEMOS MÁS TARDE', 'NOS VEMOS MÁS TARDE.MP3', 14);
INSERT INTO ENGLISH_LAB.VOCABULARY (ID_LESSON, ENGLISH_VALUE, ENGLISH_SOUND, SPANISH_VALUE, SPANISH_SOUND, "ORDER") VALUES ('5_1', 'TILL NEXT TIME', 'TILL NEXT TIME.MP3', 'HASTA LA PRÓXIMA', 'HASTA LA PRÓXIMA.MP3', 15);
