DELETE FROM ENGLISH_LAB.VOCABULARY WHERE ID_LESSON = '7_1';

/*INSERTS*/
INSERT INTO ENGLISH_LAB.VOCABULARY (ID_LESSON, ENGLISH_VALUE, ENGLISH_SOUND, SPANISH_VALUE, SPANISH_SOUND, "ORDER") VALUES ('7_1', 'JANUARY', 'JANUARY.MP3', 'ENERO', 'ENERO.MP3', 1);
INSERT INTO ENGLISH_LAB.VOCABULARY (ID_LESSON, ENGLISH_VALUE, ENGLISH_SOUND, SPANISH_VALUE, SPANISH_SOUND, "ORDER") VALUES ('7_1', 'FEBRUARY', 'FEBRUARY.MP3', 'FEBRERO', 'FEBRERO.MP3', 2);
INSERT INTO ENGLISH_LAB.VOCABULARY (ID_LESSON, ENGLISH_VALUE, ENGLISH_SOUND, SPANISH_VALUE, SPANISH_SOUND, "ORDER") VALUES ('7_1', 'MARCH', 'MARCH.MP3', 'MARZO', 'MARZO.MP3', 3);
INSERT INTO ENGLISH_LAB.VOCABULARY (ID_LESSON, ENGLISH_VALUE, ENGLISH_SOUND, SPANISH_VALUE, SPANISH_SOUND, "ORDER") VALUES ('7_1', 'APRIL', 'APRIL.MP3', 'ABRIL', 'ABRIL.MP3', 4);
INSERT INTO ENGLISH_LAB.VOCABULARY (ID_LESSON, ENGLISH_VALUE, ENGLISH_SOUND, SPANISH_VALUE, SPANISH_SOUND, "ORDER") VALUES ('7_1', 'MAY', 'MAY.MP3', 'MAYO', 'MAYO.MP3', 5);
INSERT INTO ENGLISH_LAB.VOCABULARY (ID_LESSON, ENGLISH_VALUE, ENGLISH_SOUND, SPANISH_VALUE, SPANISH_SOUND, "ORDER") VALUES ('7_1', 'JUNE', 'JUNE.MP3', 'JUNIO', 'JUNIO.MP3', 6);
INSERT INTO ENGLISH_LAB.VOCABULARY (ID_LESSON, ENGLISH_VALUE, ENGLISH_SOUND, SPANISH_VALUE, SPANISH_SOUND, "ORDER") VALUES ('7_1', 'JULY', 'JULY.MP3', 'JULIO', 'JULIO.MP3', 7);
INSERT INTO ENGLISH_LAB.VOCABULARY (ID_LESSON, ENGLISH_VALUE, ENGLISH_SOUND, SPANISH_VALUE, SPANISH_SOUND, "ORDER") VALUES ('7_1', 'AUGUST', 'AUGUST.MP3', 'AGOSTO', 'AGOSTO.MP3', 8);
INSERT INTO ENGLISH_LAB.VOCABULARY (ID_LESSON, ENGLISH_VALUE, ENGLISH_SOUND, SPANISH_VALUE, SPANISH_SOUND, "ORDER") VALUES ('7_1', 'SEPTEMBER', 'SEPTEMBER.MP3', 'SEPTIEMBRE', 'SEPTIEMBRE.MP3', 9);
INSERT INTO ENGLISH_LAB.VOCABULARY (ID_LESSON, ENGLISH_VALUE, ENGLISH_SOUND, SPANISH_VALUE, SPANISH_SOUND, "ORDER") VALUES ('7_1', 'OCTOBER', 'OCTOBER.MP3', 'OCTUBRE', 'OCTUBRE.MP3', 10);
INSERT INTO ENGLISH_LAB.VOCABULARY (ID_LESSON, ENGLISH_VALUE, ENGLISH_SOUND, SPANISH_VALUE, SPANISH_SOUND, "ORDER") VALUES ('7_1', 'NOVEMBER', 'NOVEMBER.MP3', 'NOVIEMBRE', 'NOVIEMBRE.MP3', 11);
INSERT INTO ENGLISH_LAB.VOCABULARY (ID_LESSON, ENGLISH_VALUE, ENGLISH_SOUND, SPANISH_VALUE, SPANISH_SOUND, "ORDER") VALUES ('7_1', 'DECEMBER', 'DECEMBER.MP3', 'DICIEMBRE', 'DICIEMBRE.MP3', 12);