DELETE FROM ENGLISH_LAB.VOCABULARY WHERE ID_LESSON = '6_1';

/*INSERTS*/
INSERT INTO ENGLISH_LAB.VOCABULARY (ID_LESSON, ENGLISH_VALUE, ENGLISH_SOUND, SPANISH_VALUE, SPANISH_SOUND, "ORDER") VALUES ('6_1', 'MONDAY', 'MONDAY.MP3', 'LUNES', 'LUNES.MP3', 1);
INSERT INTO ENGLISH_LAB.VOCABULARY (ID_LESSON, ENGLISH_VALUE, ENGLISH_SOUND, SPANISH_VALUE, SPANISH_SOUND, "ORDER") VALUES ('6_1', 'TUESDAY', 'TUESDAY.MP3', 'MARTES', 'MARTES.MP3', 2);
INSERT INTO ENGLISH_LAB.VOCABULARY (ID_LESSON, ENGLISH_VALUE, ENGLISH_SOUND, SPANISH_VALUE, SPANISH_SOUND, "ORDER") VALUES ('6_1', 'WEDNESDAY', 'WEDNESDAY.MP3', 'MIÉRCOLES', 'MIÉRCOLES.MP3', 3);
INSERT INTO ENGLISH_LAB.VOCABULARY (ID_LESSON, ENGLISH_VALUE, ENGLISH_SOUND, SPANISH_VALUE, SPANISH_SOUND, "ORDER") VALUES ('6_1', 'THURSDAY', 'THURSDAY.MP3', 'JUEVES', 'JUEVES.MP3', 4);
INSERT INTO ENGLISH_LAB.VOCABULARY (ID_LESSON, ENGLISH_VALUE, ENGLISH_SOUND, SPANISH_VALUE, SPANISH_SOUND, "ORDER") VALUES ('6_1', 'FRIDAY', 'FRIDAY.MP3', 'VIERNES', 'VIERNES.MP3', 5);
INSERT INTO ENGLISH_LAB.VOCABULARY (ID_LESSON, ENGLISH_VALUE, ENGLISH_SOUND, SPANISH_VALUE, SPANISH_SOUND, "ORDER") VALUES ('6_1', 'SATURDAY', 'SATURDAY.MP3', 'SÁBADO', 'SÁBADO.MP3', 6);
INSERT INTO ENGLISH_LAB.VOCABULARY (ID_LESSON, ENGLISH_VALUE, ENGLISH_SOUND, SPANISH_VALUE, SPANISH_SOUND, "ORDER") VALUES ('6_1', 'SUNDAY', 'SUNDAY.MP3', 'DOMINGO', 'DOMINGO.MP3', 7);