DELETE FROM LEARNING_ENGLISH.VOCABULARY WHERE VO_ID_LESSON = '25_1';

/*INSERTS*/
INSERT INTO LEARNING_ENGLISH.VOCABULARY (VO_ID_LESSON, VO_ENGLISH_VALUE, VO_ENGLISH_SOUND, VO_SPANISH_VALUE, VO_SPANISH_SOUND, VO_IMG, VO_ORDER) VALUES ('25_1','SPRING','SPRING.mp3','PRIMAVERA','PRIMAVERA.mp3','SPRING.jpg','1');
INSERT INTO LEARNING_ENGLISH.VOCABULARY (VO_ID_LESSON, VO_ENGLISH_VALUE, VO_ENGLISH_SOUND, VO_SPANISH_VALUE, VO_SPANISH_SOUND, VO_IMG, VO_ORDER) VALUES ('25_1','SUMMER','SUMMER.mp3','VERANO','VERANO.mp3','SUMMER.jpg','2');
INSERT INTO LEARNING_ENGLISH.VOCABULARY (VO_ID_LESSON, VO_ENGLISH_VALUE, VO_ENGLISH_SOUND, VO_SPANISH_VALUE, VO_SPANISH_SOUND, VO_IMG, VO_ORDER) VALUES ('25_1','AUTUMN/FALL','AUTUMN-FALL.mp3','OTOÑO','OTOÑO.mp3','AUTUMN-FALL.jpg','3');
INSERT INTO LEARNING_ENGLISH.VOCABULARY (VO_ID_LESSON, VO_ENGLISH_VALUE, VO_ENGLISH_SOUND, VO_SPANISH_VALUE, VO_SPANISH_SOUND, VO_IMG, VO_ORDER) VALUES ('25_1','WINTER','WINTER.mp3','INVIERNO','INVIERNO.mp3','WINTER.jpg','4');


