DELETE FROM LEARNING_ENGLISH.VOCABULARY WHERE VO_ID_LESSON = '7_1';

/*INSERTS*/
INSERT INTO LEARNING_ENGLISH.VOCABULARY (VO_ID_LESSON, VO_ENGLISH_VALUE, VO_ENGLISH_SOUND, VO_SPANISH_VALUE, VO_SPANISH_SOUND, VO_ORDER) VALUES ('7_1', 'JANUARY', 'JANUARY.MP3', 'ENERO', 'ENERO.MP3', 1);
INSERT INTO LEARNING_ENGLISH.VOCABULARY (VO_ID_LESSON, VO_ENGLISH_VALUE, VO_ENGLISH_SOUND, VO_SPANISH_VALUE, VO_SPANISH_SOUND, VO_ORDER) VALUES ('7_1', 'FEBRUARY', 'FEBRUARY.MP3', 'FEBRERO', 'FEBRERO.MP3', 2);
INSERT INTO LEARNING_ENGLISH.VOCABULARY (VO_ID_LESSON, VO_ENGLISH_VALUE, VO_ENGLISH_SOUND, VO_SPANISH_VALUE, VO_SPANISH_SOUND, VO_ORDER) VALUES ('7_1', 'MARCH', 'MARCH.MP3', 'MARZO', 'MARZO.MP3', 3);
INSERT INTO LEARNING_ENGLISH.VOCABULARY (VO_ID_LESSON, VO_ENGLISH_VALUE, VO_ENGLISH_SOUND, VO_SPANISH_VALUE, VO_SPANISH_SOUND, VO_ORDER) VALUES ('7_1', 'APRIL', 'APRIL.MP3', 'ABRIL', 'ABRIL.MP3', 4);
INSERT INTO LEARNING_ENGLISH.VOCABULARY (VO_ID_LESSON, VO_ENGLISH_VALUE, VO_ENGLISH_SOUND, VO_SPANISH_VALUE, VO_SPANISH_SOUND, VO_ORDER) VALUES ('7_1', 'MAY', 'MAY.MP3', 'MAYO', 'MAYO.MP3', 5);
INSERT INTO LEARNING_ENGLISH.VOCABULARY (VO_ID_LESSON, VO_ENGLISH_VALUE, VO_ENGLISH_SOUND, VO_SPANISH_VALUE, VO_SPANISH_SOUND, VO_ORDER) VALUES ('7_1', 'JUNE', 'JUNE.MP3', 'JUNIO', 'JUNIO.MP3', 6);
INSERT INTO LEARNING_ENGLISH.VOCABULARY (VO_ID_LESSON, VO_ENGLISH_VALUE, VO_ENGLISH_SOUND, VO_SPANISH_VALUE, VO_SPANISH_SOUND, VO_ORDER) VALUES ('7_1', 'JULY', 'JULY.MP3', 'JULIO', 'JULIO.MP3', 7);
INSERT INTO LEARNING_ENGLISH.VOCABULARY (VO_ID_LESSON, VO_ENGLISH_VALUE, VO_ENGLISH_SOUND, VO_SPANISH_VALUE, VO_SPANISH_SOUND, VO_ORDER) VALUES ('7_1', 'AUGUST', 'AUGUST.MP3', 'AGOSTO', 'AGOSTO.MP3', 8);
INSERT INTO LEARNING_ENGLISH.VOCABULARY (VO_ID_LESSON, VO_ENGLISH_VALUE, VO_ENGLISH_SOUND, VO_SPANISH_VALUE, VO_SPANISH_SOUND, VO_ORDER) VALUES ('7_1', 'SEPTEMBER', 'SEPTEMBER.MP3', 'SEPTIEMBRE', 'SEPTIEMBRE.MP3', 9);
INSERT INTO LEARNING_ENGLISH.VOCABULARY (VO_ID_LESSON, VO_ENGLISH_VALUE, VO_ENGLISH_SOUND, VO_SPANISH_VALUE, VO_SPANISH_SOUND, VO_ORDER) VALUES ('7_1', 'OCTOBER', 'OCTOBER.MP3', 'OCTUBRE', 'OCTUBRE.MP3', 10);
INSERT INTO LEARNING_ENGLISH.VOCABULARY (VO_ID_LESSON, VO_ENGLISH_VALUE, VO_ENGLISH_SOUND, VO_SPANISH_VALUE, VO_SPANISH_SOUND, VO_ORDER) VALUES ('7_1', 'NOVEMBER', 'NOVEMBER.MP3', 'NOVIEMBRE', 'NOVIEMBRE.MP3', 11);
INSERT INTO LEARNING_ENGLISH.VOCABULARY (VO_ID_LESSON, VO_ENGLISH_VALUE, VO_ENGLISH_SOUND, VO_SPANISH_VALUE, VO_SPANISH_SOUND, VO_ORDER) VALUES ('7_1', 'DECEMBER', 'DECEMBER.MP3', 'DICIEMBRE', 'DICIEMBRE.MP3', 12);