CREATE TABLE LEARNING_ENGLISH.VOCABULARY(
VO_ID SERIAL,
VO_ID_LESSON VARCHAR(10),

VO_ENGLISH_VALUE VARCHAR(100),
VO_ENGLISH_PRONUNCIATION VARCHAR(100),
VO_ENGLISH_SOUND VARCHAR(100),

VO_SPANISH_VALUE VARCHAR(100),
VO_SPANISH_PRONUNCIATION VARCHAR(100),
VO_SPANISH_SOUND VARCHAR(100),

VO_OTHER_VALUE VARCHAR(100),
VO_IMG VARCHAR(100),
VO_ORDER INTEGER
);

/*PRIMARY KEY*/
ALTER TABLE LEARNING_ENGLISH.VOCABULARY ADD CONSTRAINT VOCABULARY_PK PRIMARY KEY (VO_ID);
/*FOREIGN KEYS*/
ALTER TABLE LEARNING_ENGLISH.VOCABULARY ADD CONSTRAINT FK_VOCA_LESS FOREIGN KEY ( VO_ID_LESSON ) REFERENCES LEARNING_ENGLISH.LESSON ( LE_ID ) ON UPDATE CASCADE;
/*UNIQUE*/
ALTER TABLE LEARNING_ENGLISH.VOCABULARY ADD CONSTRAINT VOCABULARY_UN UNIQUE (VO_ID_LESSON, VO_ENGLISH_VALUE, VO_SPANISH_VALUE);

/*COMMENT THE TABLE*/
COMMENT ON TABLE LEARNING_ENGLISH.VOCABULARY IS 'This table stores the vocabulary';
/*COMMENT THE FIELDS*/
COMMENT ON COLUMN LEARNING_ENGLISH.VOCABULARY.VO_ID IS 'Primary key of the table VOCABULARY.';
COMMENT ON COLUMN LEARNING_ENGLISH.VOCABULARY.VO_ID_LESSON IS 'Foreign key of the table LESSON.';

COMMENT ON COLUMN LEARNING_ENGLISH.VOCABULARY.VO_ENGLISH_VALUE IS 'Field that saves the value in english.';
COMMENT ON COLUMN LEARNING_ENGLISH.VOCABULARY.VO_ENGLISH_PRONUNCIATION IS 'Field that saves the pronunciation of the word in english.';
COMMENT ON COLUMN LEARNING_ENGLISH.VOCABULARY.VO_ENGLISH_SOUND IS 'Field that saves the sound of the word in english.';

COMMENT ON COLUMN LEARNING_ENGLISH.VOCABULARY.VO_SPANISH_VALUE IS 'Field that saves the value in spanish.';
COMMENT ON COLUMN LEARNING_ENGLISH.VOCABULARY.VO_SPANISH_PRONUNCIATION IS 'Field that saves the pronunciation of the word in spanish.';
COMMENT ON COLUMN LEARNING_ENGLISH.VOCABULARY.VO_SPANISH_SOUND IS 'Field that saves the sound of the word in spanish.';

COMMENT ON COLUMN LEARNING_ENGLISH.VOCABULARY.VO_OTHER_VALUE IS 'Field that saves other value.';

COMMENT ON COLUMN LEARNING_ENGLISH.VOCABULARY.VO_IMG IS 'Field that saves the image of the object.';
COMMENT ON COLUMN LEARNING_ENGLISH.VOCABULARY.VO_ORDER IS 'Field that saves the order of the vocabulary.';