DELETE FROM LEARNING_ENGLISH.VOCABULARY WHERE VO_ID_LESSON = '6_1';

/*INSERTS*/
INSERT INTO LEARNING_ENGLISH.VOCABULARY (VO_ID_LESSON, VO_ENGLISH_VALUE, VO_ENGLISH_SOUND, VO_SPANISH_VALUE, VO_SPANISH_SOUND, VO_ORDER) VALUES ('6_1', 'MONDAY', 'MONDAY.MP3', 'LUNES', 'LUNES.MP3', 1);
INSERT INTO LEARNING_ENGLISH.VOCABULARY (VO_ID_LESSON, VO_ENGLISH_VALUE, VO_ENGLISH_SOUND, VO_SPANISH_VALUE, VO_SPANISH_SOUND, VO_ORDER) VALUES ('6_1', 'TUESDAY', 'TUESDAY.MP3', 'MARTES', 'MARTES.MP3', 2);
INSERT INTO LEARNING_ENGLISH.VOCABULARY (VO_ID_LESSON, VO_ENGLISH_VALUE, VO_ENGLISH_SOUND, VO_SPANISH_VALUE, VO_SPANISH_SOUND, VO_ORDER) VALUES ('6_1', 'WEDNESDAY', 'WEDNESDAY.MP3', 'MIÉRCOLES', 'MIÉRCOLES.MP3', 3);
INSERT INTO LEARNING_ENGLISH.VOCABULARY (VO_ID_LESSON, VO_ENGLISH_VALUE, VO_ENGLISH_SOUND, VO_SPANISH_VALUE, VO_SPANISH_SOUND, VO_ORDER) VALUES ('6_1', 'THURSDAY', 'THURSDAY.MP3', 'JUEVES', 'JUEVES.MP3', 4);
INSERT INTO LEARNING_ENGLISH.VOCABULARY (VO_ID_LESSON, VO_ENGLISH_VALUE, VO_ENGLISH_SOUND, VO_SPANISH_VALUE, VO_SPANISH_SOUND, VO_ORDER) VALUES ('6_1', 'FRIDAY', 'FRIDAY.MP3', 'VIERNES', 'VIERNES.MP3', 5);
INSERT INTO LEARNING_ENGLISH.VOCABULARY (VO_ID_LESSON, VO_ENGLISH_VALUE, VO_ENGLISH_SOUND, VO_SPANISH_VALUE, VO_SPANISH_SOUND, VO_ORDER) VALUES ('6_1', 'SATURDAY', 'SATURDAY.MP3', 'SÁBADO', 'SÁBADO.MP3', 6);
INSERT INTO LEARNING_ENGLISH.VOCABULARY (VO_ID_LESSON, VO_ENGLISH_VALUE, VO_ENGLISH_SOUND, VO_SPANISH_VALUE, VO_SPANISH_SOUND, VO_ORDER) VALUES ('6_1', 'SUNDAY', 'SUNDAY.MP3', 'DOMINGO', 'DOMINGO.MP3', 7);